# .cirrus.yml

task:
  name: Release
  only_if: $BRANCH == "main"
  # depends_on:
  container:
    image: gembaadvantage/uplift:latest
  script: uplift release
  environment:
    GITHUB_TOKEN: ENCRYPTED[!1497b201beb7fb1075827a5e47896cd2d82076bdba50a003b06be04333d9b17fb80475fccb8d7744dad71a55a4e2c293!]
# git remote set-url origin "https://oauth2:${GL_UPLIFT}@$PROJECT_URL.git"
