# .travis.yml

# Setup the pipeline based on your chosen language
language: go

git:
  depth: false

before_install:
  - |
    curl https://raw.githubusercontent.com/gembaadvantage/uplift/master/scripts/install > install
    chmod 700 install
    sudo ./install

deploy:
  - provider: script
    skip_cleanup: true
    script: uplift release
    on:
      branch: main
      condition: $TRAVIS_OS_NAME = linux

env:
  global:
    secure: qOUoZRntjeD4xn6g1bAG1FsPFqGMoUXDlWROmYGjYYSuMwquO6zWLZLY/8SDakE6SFUSnXWEtAiDcvFBDojvjStS+pF0w/XEntNFn3AtegGON0cm2BToWA7VEhzVYbAd0iQEdCmko/2oMQpqXBUpLQSjFqjxmc0VIu1irVwCinRoJbUsXJi15f90W8d7jLnUbj3A1EzSOHIdRcbw6AElY2lOpGUny9q5PapBeDTNyIHD9bLO7rqHO/zhnGPs/hAzlrwTfrro7k13KhJqB8YXHzevrQDaZfU5WHhne28rDt061kVqHIsUbKZ1WhYM3KW61VcNd4vgjfkIGFqfwAgTKJpHjIT5eTSpX6eH11eKQrC8kpHLv5p0OV7gtrWL9EmcnHwbXVwNltkm8IhfubAqzo/hABf6kKR6N7QTcymtQOEolUKtqlImD5SL9T99JZOLRujUhZSIWm1NCUOwUGuF9o1GIjZrkZwsXeA33OL/Amt5RwXelYzvnTayuZK+722rMkq93HFOor9Y5As5VUdrwJGb2vMsC39gF8zl/gE57gpRD7yDB7yUlU9oUkiEJHEYQNhAKThWatSsx+quhvlJGS9KU4ZwrwwHwikyjMpPelz+hqn45e6o0ZIrxccH1Lel66i2Bed4TkIX2/MViZqX+oNZL1MjSbLz6TQkiEJ5wMo=
