# .travis.yml

# Setup the pipeline based on your chosen language
language: go

git:
  depth: false

before_install:
  - |
    curl https://raw.githubusercontent.com/gembaadvantage/uplift/master/scripts/install > install
    chmod 700 install
    sudo ./install

script:
  - git remote set-url origin https://${GH_UPLIFT}@github.com/${TRAVIS_REPO_SLUG}.git
  - git checkout $TRAVIS_BRANCH

deploy:
  - provider: script
    skip_cleanup: true
    script: uplift release
    on:
      branch: main
      condition: $TRAVIS_OS_NAME = linux

env:
  global:
    secure: 0l3pSB3Du+YQuV4Gf0R2PoPlrX5PCsJ+4H775aDy2GnmuQhpEbab4KmgUJu6P4S7fy1ROkSMo7GcwXDyQdhKFOMS7Q2Bu3IvG2ziAbG4lsZQkMqiDTVQDjkO3eb+ZilA7PTT0oG3JTXoEBn57cftA5Cnvo53Jolp+XCSWtQDPWaYeSCC5TgH7mviO+wziJ1HCUd9glrh+9B1Sy1KhdrsWxdkFXeKLD4kQPmvBu4gcgGLrWCvTOWpqrvFBQES7BMKHI1vIPUEpIKRzuMZkif7JgefIcpD4WPwrJ9GkgS/QXYNtqRKfRlzGhoTAZ8nzrDbrhAwDVqoSsRlcq28zVNIhoDzy6IwJBbYkkkQeMKL65DLWX+6PN986MloXTAX/Zq+1dupuxFdjWS1pixRTtMrJclpstgBh1XrPNzm91Wp82GfjFfktbe5z0MYm90hJwgUG59RjexIou20UZTNBLtfdnEj7Z8/poMBO/dTdBUtTQALbZbdncoIoPTvTpRfLJZhgpkbYJwcSxHeIa7rgWLs/e5LX9IdsVY8AO6Lw65ziw9/SjaKpc80Mm9X+QRkr1bg8yFgHCk4Abg1JJ0WRWiWw6F0z7F9MOhXWCS+u+P5lsUzqyEsaLBObpckT51gYmCRENnObt3jYbWsj2aq+GmObD35BcP7v62XwnTQCtJbqY8=
