# .travis.yml

# Setup the pipeline based on your chosen language
language: go

git:
  depth: false

before_install:
  - |
    curl https://raw.githubusercontent.com/gembaadvantage/uplift/master/scripts/install > install
    chmod 700 install
    sudo ./install

deploy:
  - provider: script
    skip_cleanup: true
    script: uplift release
    on:
      branch: main
      condition: $TRAVIS_OS_NAME = linux
