steps:
  # Ensure clone contains required build history
  - name: gcr.io/cloud-builders/git
    args: ["fetch", "--unshallow"]

  - name: gembaadvantage/uplift
    entrypoint: /bin/sh
    args: ["-c", "git checkout $BRANCH && uplift release"]
    env:
      - "BUILD=$BUILD_ID"
      - "PROJECT_ID=$PROJECT_ID"
      - "PROJECT_NUMBER=$PROJECT_NUMBER"
      - "REV=$REVISION_ID"
      - "BRANCH=$BRANCH_NAME"
