version: "1.0"
stages:
  - prepare
  - prerelease
  - release
steps:
  main_clone:
    title: "Cloning main repository..."
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    stage: prepare
  configure_git:
    title: "Configure Git"
    image: alpine/git:latest
    commands:
      - git config --get remote.origin.url
      - git remote set-url origin "https://${GH_UPLIFT}@github.com/${CF_REPO_OWNER}/${CF_REPO_NAME}"
      - git remote -v
    stage: prerelease
  uplift:
    title: "Release"
    stage: release
    image: "gembaadvantage/uplift"
    commands:
      - uplift release
