version: "1.0"
stages:
  - prepare
  - release
steps:
  main_clone:
    title: "Cloning main repository..."
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: prepare
  uplift:
    title: "Release"
    stage: release
    image: "gembaadvantage/uplift"
    commands:
      - REMOTE_URL=$(git config --get remote.origin.url)
      - CLONE_URL=${REMOTE_URL#"https://"}
      - git remote set-url origin "https://${GH_UPLIFT}@${CLONE_URL}"
      - uplift release
