# .circleci/config.yml

version: 2.1
workflows:
  main:
    jobs:
      - release:
          filters:
            branches:
              # Only trigger on the main branch
              only: main
jobs:
  release:
    docker:
      # Can use whatever base image you like
      - image: cimg/go:1.18
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3b:c7:44:c9:34:ab:a4:fd:6c:33:4e:a7:7a:97:79:55"
      - checkout
      - run: |
          curl https://raw.githubusercontent.com/gembaadvantage/uplift/master/scripts/install > install
          chmod 700 install
          sudo ./install
      - run: uplift release
